In [3]:
import pandas as pd
import numpy as np

In [4]:
gongo = pd.read_csv('..\\concatdataset\\gongo_df.csv')

### 필요없는 열 삭제

In [5]:
# 직무(복수선택) 열 삭제
gongo.drop(['직무(복수선택)'],axis=1, inplace=True)

In [7]:
# check
len(gongo)

5744

### 데이터 타입 변환

In [8]:
# '스킬' 열 str -> 리스트로 변환
for i in range(len(gongo)):
  gongo['스킬'][i] = gongo['스킬'][i].strip("[").strip("]").replace("'","").split(", ")

In [9]:
# '직무_lv1' 열 str -> 리스트로 변환
for i in range(len(gongo)):
  gongo['직무_lv1'][i] = gongo['직무_lv1'][i].strip("[").strip("]").replace("'","").split(", ")

In [10]:
# '직무_lv2' 열 str -> 리스트로 변환
for i in range(len(gongo)):
  gongo['직무_lv2'][i] = gongo['직무_lv2'][i].strip("[").strip("]").replace("'","").split(", ")

### 직무_lv1 unique 값 찾기

In [12]:
# 직무_lv1 열의 value_counts 구하기
job_lv1 = gongo['직무_lv1'].value_counts().index

# 직무_lv1이 하나의 값만 갖는 경우 리스트에 추가
job_lv1_list = []
for job in job_lv1:
  if len(job)==1:
    job_lv1_list.append(job[0])
job_lv1_list

['개발',
 '마케팅/시장조사',
 '기획/경영',
 '영업/제휴',
 '디자인',
 '데이터',
 '인사/총무',
 '서비스/고객지원',
 '금융/재무',
 '미디어/홍보',
 '생산/제조',
 '생산관리/품질관리',
 '엔지니어링',
 '유통/무역',
 '연구개발',
 '법률/법무',
 '교육',
 '전문직',
 '의약']

### 직무_lv2 unique 값 찾기

In [ ]:
# 직무_lv2 열의 value_counts 구하기
job_lv2 = gongo['직무_lv2'].value_counts().index

# 직무_lv1이 하나의 값만 갖는 경우 리스트에 추가
job_lv2_list = []
for job in job_lv2:
  if len(job)==1:
    job_lv2_list.append(job[0])
job_lv2_list

### 직무 lv1 데이터프레임 생성

In [23]:
# 직무 lv1 데이터프레임 생성
job_lv1_df = pd.DataFrame(columns = job_lv1_list)
job_lv1_df
job_lv1_df['index'] = gongo.index

In [25]:
# 직무 lv1 데이터프레임에 각 데이터별 해당되는 직무 컬럼이 있으면 1값 부여
for i, job in enumerate(gongo['직무_lv1']):
  for category_job in job_lv1_list:
    if category_job in job:
      job_lv1_df.loc[i,category_job] = 1
job_lv1_df.fillna(0, inplace=True)

In [26]:
# check
len(job_lv1_df)

5744

In [27]:
# csv파일로 저장
job_lv1_df.to_csv('.\\job_lv1_df.csv', encoding="utf-8-sig", index=False)

### 직무 lv2 데이터프레임 생성

In [28]:
# 직무 lv2 데이터프레임 생성
job_lv2_df = pd.DataFrame(columns = job_lv2_list)
job_lv2_df
job_lv2_df['index'] = gongo.index

In [29]:
# 직무 lv2 데이터프레임에 각 데이터별 해당되는 직무 컬럼이 있으면 1값 부여
for i, job in enumerate(gongo['직무_lv2']):
  for category_job in job_lv2_list:
    if category_job in job:
      job_lv2_df.loc[i,category_job] = 1
job_lv2_df.fillna(0, inplace=True)

In [30]:
# check
len(job_lv2_df)

5744

In [31]:
# csv파일로 저장
job_lv2_df.to_csv('.\\job_lv2_df.csv', encoding="utf-8-sig", index=False)

In [32]:
job_lv1_df = pd.read_csv('.\\job_lv1_df.csv')
job_lv2_df = pd.read_csv('.\\job_lv2_df.csv')

In [33]:
job_lv1_df[:3]

,개발,마케팅/시장조사,기획/경영,영업/제휴,디자인,데이터,인사/총무,서비스/고객지원,금융/재무,미디어/홍보,생산/제조,생산관리/품질관리,엔지니어링,유통/무역,연구개발,법률/법무,교육,전문직,의약,index
0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2

In [34]:
for column in job_lv1_df.columns:
  print(column,len(job_lv1_df[job_lv1_df[column]==1]))

개발 1838
마케팅/시장조사 921
기획/경영 658
영업/제휴 633
디자인 430
데이터 189
인사/총무 157
서비스/고객지원 164
금융/재무 154
미디어/홍보 130
생산/제조 120
생산관리/품질관리 90
엔지니어링 88
유통/무역 86
연구개발 91
법률/법무 24
교육 32
전문직 19
의약 8
index 1

In [35]:
for column in job_lv2_df.columns:
  print(column,len(job_lv2_df[job_lv2_df[column]==1]))

소프트웨어 개발 686
마케팅 530
백엔드 개발 377
프론트엔드 개발 301
서비스 기획 243
PM/PO 202
상품개발/기획/MD 234
국내영업 249
웹개발 289
네트워크/보안/운영 223
영업기획/관리/지원 286
UI/UX/GUI디자인 167
고객지원/CS 118
QA(Quality Assurance) 74
하드웨어 개발 91
머신러닝 엔지니어 68
사업 기획 167
온라인마케팅 306
클라우드 개발 86
데이터 분석가 76
경영기획/전략 110
기술영업 174
광고기획/카피라이터 49
해외영업 100
기술지원 89
안드로이드 개발 116
브랜드마케팅 228
방송연출/PD/감독  42
경영지원 52
웹디자인 114
IT/솔루션영업  136
전략 기획 127
iOS 개발 93
판매/매장관리 68
재무기획/재무분석 93
ERP 33
인사관리 92
그래픽디자인 96
기계설계 33
품질관리 42
데이터 엔지니어 42
전기/전자/제어  26
전자/반도체 50
회계사 43
물류/유통/운송 49
브랜드디자인 101
기계/기계설비  28
구매/자재/재고 47
기타 서비스직 30
경리/출납/결산  79
인재개발/교육 40
홍보 30
소프트웨어아키텍트 108
게임개발 25
컨설팅 29
생산관리 27
광고/시각디자인 74
생산/제조 19
DBA(Database Admin.) 41
유지/수리/정비 23
제품/산업디자인 52
반도체/디스플레이 33
데이터 사이언티스트 26
총무/사무 49
패션/섬유디자인 15
영상/모션디자인 32
교육기획/교재개발 29
전기설계 10
채용 34
안전관리 10
전략마케팅 105
마케팅커뮤니케이션 123
CRM 51
시공/감리/공무 9
고객지원/Desk 34
외식업/식음료 11
기계 12
VR 엔지니어 7
변호사 13
유전공학/생명/생물 13
건축/설계디자인 8
바이오/제약/식품  8
통역/번역 6
전시/무대디자인 5
CTO (Chief Technology Officer) 9
식품/제약 11
시장조사/분석 79
건축설계 9
품질보증 16
빅데이터 엔지니어 11
부동산/공인중개사 8
웹퍼블리셔 20
채권관리 8
생산/품질기획 15
법률/법무 13
전기 12
토목설계 6
호텔리어 9
사진/포토그래퍼/카메라기자 4
간호사 4
공정관리 6
게임 기획 4
안경/렌즈/광학  3
제어 3
캐릭터디자인 3
문화 기획 12
화학/화공/섬유 3
애니메이션디자인 11
포장/조립  7
의약영업 13
조직문화 42
특허/변리사 4
출판/편집디자인 30
요리사/푸드스타일리스트 2
문화/예술/스포츠 2
간호조무사  2
기자 7
대외협력 7
BI 엔지니어 4
비서/안내/수행원  2
세무사 2
감사 2
헤드헌터 1
손익/리스크관리 10
약사/한약사 1
CEO (Chief Executive Officer) 1
화학/에너지  1
수출입관리 16
노무 16
행사 기획 13
환경/안전/보건(ESH) 1
연예/엔터테인먼트  1
인문/사회과학 1
카메라/조명/미술  1
관세사 4
배관설계 1
인쇄/출판/편집  8
자산운용가 9
비서 1
작가/시나리오  3
사무보조/문서작성  6
제과제빵사 1
제품별마케팅 27
보상 15
치기공사/치과위생사 1
금융/보험영업 4
index 1

특정 직무 컬럼 값이 1인 데이터의 index 번호 가져와서 분석하면 될 듯

### 기업 소개 ~ 우대사항 컬럼의 nan값 채우기

In [36]:
# check
gongo[:3]

,회사명,고용 형태,스킬,기업 소개,주요 업무,자격 요건,우대 사항,채용 절차,복리후생,회사위치,직무_lv1,직무_lv2
0,캐롯손해보험(주),정규직,"[Oracle, BI, SQL, dw, etl]","캐롯손해보험은 한화, SKT, 현대자동차, 알토스벤쳐스, 스틱인베스트먼트 등 대형 ...",• 캐롯 주행/계약 관련 지표 생성 및 제공해요.\r\n• Data-warehous...,• BI 및 ETL 관련 분야 경력 5년 이상이신 분이 필요해요.\r\n• DW 데...,• BI 툴 활용 및 Hadoop에 대한 연동을 이해하신 분이면 좋아요.\r\n• ...,"• 해당 직무는 수시채용으로, 채용 완료 시 공고가 마감될 수 있어요.\r\n• 지...",[성장을 위한 휴식]\r\n• 매년 복지포인트 200만원\r\n• 설 차례비 지급\...,"서울 중구 을지로100 파인에비뉴 B동 20층, 캐롯손해보험",[데이터],[BI 엔지니어]
1,(주)웅진,정규직,[POWER BI],NaN,"- MS Power Platform 프로젝트 수행 및 기술지원 (Automate, ...",【지원자격】 \r\n - 모집직급: 대리~과장 \r\n - MS Power Plat...,NaN,NaN,NaN,서울 중구 청계천로 24,"[개발, 데이터]","[클라우드 개발, BI 엔지니어]"
2,잡플래닛,정규직,"[데이터분석, BI, python, SQL, Tableau, POWER BI]",더 나은 선택은 없을까?\r\n 지금 이 순간에도 잡플래닛을 방문하는 월 300만명...,[조직소개]\r\n잡플래닛의 데이터 조직은 Data 1st전략으로 서비스의 핵심 자...,"[자격 조건]\r\n• SQL 상급, 파이썬 중급\r\n• Data Visualiz...","[우대 사항]\r\n• Statistics, Econometrics, Applied...",[전형 프로세스]\r\n• 서류전형 -> 1차 실무 인터뷰 -> 2차 협업부서 인터...,- 분 단위 시차 출퇴근제 (오전 7시~ 오전 10시 사이 자율 출퇴근)\r\n ...,"서울특별시 강남구 테헤란로 509 엔씨타워 I, 10층",[데이터],[BI 엔지니어]

In [37]:
# 컬럼별 nan 개수
for column_name in gongo.columns:
  print(column_name, gongo[column_name].isna().sum())

회사명 0
고용 형태 0
스킬 0
기업 소개 537
주요 업무 0
자격 요건 0
우대 사항 413
채용 절차 1930
복리후생 455
회사위치 36
직무_lv1 0
직무_lv2 0

보통 글이 잘못 들어간 컬럼: 기업 소개, 주요 업무, 자격 요건, 우대 사항

### 여기

In [29]:
# 원본 공고 파일 읽어오기
gongo = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/result/gongo_df.csv')

# '스킬' 열 str -> 리스트로 변환
for i in range(len(gongo)):
  gongo['스킬'][i] = gongo['스킬'][i].strip("[").strip("]").replace("'","").split(", ")

# 직무(복수선택) 열 삭제
gongo.drop(['직무(복수선택)','직무_lv1','직무_lv2'],axis=1, inplace=True)

# 자격요건+우대사항 하나의 컬럼으로 합치기
gongo['자격요건 및 우대사항'] = gongo['자격 요건']+gongo['우대 사항']

# 자격요건, 우대사항 각 컬럼 삭제
gongo.drop(['자격 요건','우대 사항'],axis=1, inplace=True)

gongo[:3] # check

,회사명,고용 형태,스킬,기업 소개,주요 업무,채용 절차,복리후생,회사위치,자격요건 및 우대사항
0,캐롯손해보험(주),정규직,"[Oracle, BI, SQL, dw, etl]","캐롯손해보험은 한화, SKT, 현대자동차, 알토스벤쳐스, 스틱인베스트먼트 등 대형 ...",• 캐롯 주행/계약 관련 지표 생성 및 제공해요.\r\n• Data-warehous...,"• 해당 직무는 수시채용으로, 채용 완료 시 공고가 마감될 수 있어요.\r\n• 지...",[성장을 위한 휴식]\r\n• 매년 복지포인트 200만원\r\n• 설 차례비 지급\...,"서울 중구 을지로100 파인에비뉴 B동 20층, 캐롯손해보험",• BI 및 ETL 관련 분야 경력 5년 이상이신 분이 필요해요.\r\n• DW 데...
1,(주)웅진,정규직,[POWER BI],NaN,"- MS Power Platform 프로젝트 수행 및 기술지원 (Automate, ...",NaN,NaN,서울 중구 청계천로 24,NaN
2,잡플래닛,정규직,"[데이터분석, BI, python, SQL, Tableau, POWER BI]",더 나은 선택은 없을까?\r\n 지금 이 순간에도 잡플래닛을 방문하는 월 300만명...,[조직소개]\r\n잡플래닛의 데이터 조직은 Data 1st전략으로 서비스의 핵심 자...,[전형 프로세스]\r\n• 서류전형 -> 1차 실무 인터뷰 -> 2차 협업부서 인터...,- 분 단위 시차 출퇴근제 (오전 7시~ 오전 10시 사이 자율 출퇴근)\r\n ...,"서울특별시 강남구 테헤란로 509 엔씨타워 I, 10층","[자격 조건]\r\n• SQL 상급, 파이썬 중급\r\n• Data Visualiz..."

In [30]:
# 사전
position = '담당업무|담당 업무|주요업무|주요 업무|직무설명|직무 설명|어떤 일을 하나요?|직무소개|직무 소개' # 주요 업무
qualification = '지원자격|지원 자격|필수조건|필수 조건|공통자격|공통 자격|자격요건|자격 요건|기술스택|기술 스택' # 자격 요건
prefer = '우대사항|우대사항' # 우대 사항

position_list = ['담당업무','담당 업무','주요업무','주요 업무','직무설명','직무 설명','어떤 일을 하나요?','직무소개','직무 소개','포지션 정보']
qualification_list = ['지원자격','지원 자격','필수조건','필수 조건','공통자격','공통 자격','자격요건','자격 요건','기술스택','기술 스택']
prefer_list = ['우대사항','우대 사항']

# company = '회사설명|회사 설명|기업 소개|기업소개|팀 소개|팀소개|조직소개|조직 소개' # 기업 소개
# hiring_process = '합류|채용절차|채용 절차' # 채용절차

In [31]:
# # 주요 업무 컬럼
# pos1 = gongo_nan['주요 업무'].str.contains(position)
# qual1 = gongo_nan['주요 업무'].str.contains(qualification)
# pref1 = gongo_nan['주요 업무'].str.contains(prefer)

# # 자격요건 및 우대사항 컬럼
# pos2 = gongo_nan['자격요건 및 우대사항'].str.contains(position)
# qual2 = gongo_nan['자격요건 및 우대사항'].str.contains(qualification)
# pref2 = gongo_nan['자격요건 및 우대사항'].str.contains(prefer)

In [32]:
# 주요 업무 컬럼
for i in range(len(gongo)):
  # 주요업무 셀에 position이 들어간 경우: 그 앞은 내용 자르기
  for pos_word in position_list:
    pos_word_index = gongo['주요 업무'][i].find(pos_word)
    if pos_word_index!=-1: # 주요업무에 다른 내용이 있는 경우
      gongo['주요 업무'][i] = gongo['주요 업무'][i][pos_word_index+len(pos_word):]

  # 주요업무 셀에 qualification이 들어간 경우: 그 뒤 내용 자르기\
  for qual_word in qualification_list:
    qual_word_index = gongo['주요 업무'][i].find(qual_word)
    if qual_word_index!=-1: # 주요업무에 다른 내용(qualication)이 있는 경우
      gongo['주요 업무'][i] = gongo['주요 업무'][i][:qual_word_index]

  # 주요 업무 셀에 prefer이 들어간 경우: 그 뒤 내용 자르기
  for prefer_word in prefer_list:
    prefer_word_index = gongo['주요 업무'][i].find(prefer_word)
    if prefer_word_index!=-1: # 다른 내용이 있는 경우
      gongo['주요 업무'][i] = gongo['주요 업무'][i][:prefer_word_index]

In [33]:
# 자격요건 및 우대사항 컬럼
# 자격요건 및 우대사항 셀에 qualification이 들어간 경우: 그 앞 내용 자르기
for i in range(len(gongo)):
  if pd.isna(gongo['자격요건 및 우대사항'][i]):
    continue
  else:
    for qual_word in qualification_list:
      qual_word_index = gongo['자격요건 및 우대사항'][i].find(qual_word)
      if qual_word_index!=-1: # 자격요건 및 우대사항 다른 내용(qualication)이 있는 경우
        gongo['자격요건 및 우대사항'][i] = gongo['자격요건 및 우대사항'][i][qual_word_index+len(qual_word):]

In [34]:
# preprocessed_gongo_final 저장
gongo.to_csv('/content/drive/MyDrive/Colab Notebooks/result/preprocessed_gongo_final.csv', encoding="utf-8-sig", index=False)

In [36]:
gongo

,회사명,고용 형태,스킬,기업 소개,주요 업무,채용 절차,복리후생,회사위치,자격요건 및 우대사항
0,캐롯손해보험(주),정규직,"[Oracle, BI, SQL, dw, etl]","캐롯손해보험은 한화, SKT, 현대자동차, 알토스벤쳐스, 스틱인베스트먼트 등 대형 ...",• 캐롯 주행/계약 관련 지표 생성 및 제공해요.\r\n• Data-warehous...,"• 해당 직무는 수시채용으로, 채용 완료 시 공고가 마감될 수 있어요.\r\n• 지...",[성장을 위한 휴식]\r\n• 매년 복지포인트 200만원\r\n• 설 차례비 지급\...,"서울 중구 을지로100 파인에비뉴 B동 20층, 캐롯손해보험",• BI 및 ETL 관련 분야 경력 5년 이상이신 분이 필요해요.\r\n• DW 데...
1,(주)웅진,정규직,[POWER BI],NaN,"- MS Power Platform 프로젝트 수행 및 기술지원 (Automate, ...",NaN,NaN,서울 중구 청계천로 24,NaN
2,잡플래닛,정규직,"[데이터분석, BI, python, SQL, Tableau, POWER BI]",더 나은 선택은 없을까?\r\n 지금 이 순간에도 잡플래닛을 방문하는 월 300만명...,"]\r\n• 전사 Business Intelligence : Dashboard, R...",[전형 프로세스]\r\n• 서류전형 -> 1차 실무 인터뷰 -> 2차 협업부서 인터...,- 분 단위 시차 출퇴근제 (오전 7시~ 오전 10시 사이 자율 출퇴근)\r\n ...,"서울특별시 강남구 테헤란로 509 엔씨타워 I, 10층","[자격 조건]\r\n• SQL 상급, 파이썬 중급\r\n• Data Visualiz..."
3,(주)포바이포,정규직,"[재무, 세무조사, 손익분석, 재무총괄]",“Into the NEW ERA” \r\n\r\n2017년에 설립된 주식회사 포바이...,• 재무총괄(회계/세무/자금)\r\n• 연간 경영계획 수립\r\n• 장기적 재무적 ...,NaN,[근무환경]\r\n- 월요일 출근 1pm - 퇴근 7pm (화~금 10am-7pm...,"서울 서초구 강남대로 479, 12층,13층,14층",• 기업재무 총괄 책임자 경험 1년 이상 \r\n• 해당 직무 경력 10년 이상\r...
4,(주)바이트랩,정규직,"[마케팅, CRM, 프로모션기획]",고객들이 꾸준히 찾는 브랜드를 운영하며 미디어커머스 업계 1위를 향한 지속 가능한 ...,• 신규 고객 유치 및 기존 고객 유지를 위한 프로모션 기획 및 운영\r\n• A/...,📄서류전형 ▶️ 👤면접 인터뷰 ▶️ ⭐처우 협의 ▶️ 🎉 합격 발표,• 조식 제공 (주 1회)\r\n• 리프레시 휴가\r\n• 시차출퇴근제\r\n• 자...,"서울 강남구 테헤란로108길 25, 4층",• 동종 업계 퍼포먼스/CRM 마케팅 관련 경력 1년 이상\r\n• CRM (퍼널 ...
...,...,...,...,...,...,...,...,...,...
5739,(주)글로카로카,정규직,"[경영지원, 회계, 세무, 경리, 자금]",글로벌 호텔이 “나의 취향에 맞는 확장형 주거공간 & 업무공간”이 된다는 미션을 통...,"• 일반 경리, 회계, 자금 관리\r\n• 정부 프로젝트 자금 관리\r\n• 경영 지원",NaN,ㆍ워케이션 1달 살기 지원\r\nㆍ모두 건강한 생활! 전직원 정밀 건강검진\r\nㆍ...,"서울 서초구 강남대로30길 17, 3층",• 유관 업무 경력자\r\n• 다양한 포지션의 팀원들과 소통하는 원활한 커뮤니케이션...
5740,동인기연(주),정규직,"[회계, 세무, 회계관리, 세무관리, IFRS]",(주)동인기연은 1992년 창립하여 ALUMINUM TUBE 및 압출 형재를 가공하...,"ㆍ회계 관리 (IFRS, 연결회계)\r\nㆍ세무 관리\r\nㆍ세무, 회계 관련 업무 전반",NaN,• 경조사 지원\r\n• 동호회 지원\r\n• 유류비 지원\r\n• 연 1회 1주간...,경기 김포시 통진읍 대곶북로 370-26,ㆍ학력 : 학사 이상 (4년제 이상)\r\nㆍ경력 : 경력 5년 이상ㆍ상장사 공시 ...
5741,(주)디홀릭커머스,정규직,"[재무, 회계, 세무, 결산, 재무제표]","세계로 뻗어가는 글로벌 이커머스 플랫폼, 디홀릭커머스에서 함께할 인재를 모십니다.\...",• 결산 총괄\r\n• 회계 및 세무 이슈 대응 총괄\r\n• 연결/별도 재무제표 ...,NaN,• 최고급 장비 및 소프트웨어 제공\r\n• 업무 참고 도서 및 개발 서적 제공\r...,서울시 중구 세종대로39 대한상공회의소 11층,• 스타트업 혹은 성장하는 기업에서 스케일업 경험이 있으신 분\r\n• 재무회계 경...
5742,루에랑(주),정규직,"[재무, 회계, 세무, 결산]","[루에랑]은, #Your First Korean Food, \r\n'가장 멋진 한국...",• 자금 업무(자금 운용 계획 및 수립)\r\n• 법인 회계 결산 및 각종 세무 신...,NaN,"▷기본 복지\r\n• 젊은 식품회사, 평균나이 29세 \r\n• 영어 이름과 직급 ...","서울 서초구 강남대로 27, 1306호","• 유관 경력 5년 이상 또는 관련 자격증(회계사, 세무사) 보유자\r\n• 매출 ..."
5743,(주)슈퍼메이커즈,정규직,"[총무, 재무, 회계, 세무, 정산, 부가가치세, 자금계획]",슈퍼키친은 슈퍼메이커즈가 2017년 설립한 HMR(가정간편식) 전문 브랜드입니다.\...,• 더존 아이큐브 전표입력\t\t\t\t\t\t\t\t\t\r\n• 법인카드 정산 ...,NaN,"• 경조휴가 및 경조사비 지원\r\n• 스낵바 운영(과자, 음료, 주류 등등)\r\...",경기도 부천시 원미로 246(춘의동),• 경력 : 1년 ~ 3년 회계결산업무 경력 보유자(사원~주임급) \t\t\t\t\...