In [1]:
import pandas as pd
import numpy as np

In [2]:
review_df = pd.read_csv('C:/TextminingProject//concatdataset/review_df.csv')
print(len(review_df))

48470

In [3]:
review_df['직무'].unique()

array(['금융/재무', '디자인', '기획/경영', '개발', '마케팅/시장조사', '전문직', '서비스/고객지원',
       '데이터', '인사/총무', '교육', '영업/제휴', '생산/제조', '미디어/홍보', '유통/무역', '기타',
       '엔지니어링', nan, '연구개발', '생산관리/품질관리', '특수계층/공공',
       '\n          현직원\n      ', '\n          전직원\n      ', '법률/법무',
       '의약'], dtype=object)

In [4]:
delete1 = review_df[review_df['직무'] == '\n          현직원\n      '].index
delete2 = review_df[review_df['직무'] == '\n          전직원\n      '].index
review_df = review_df.drop(delete1)
review_df = review_df.drop(delete2)

In [5]:
review_df = review_df.dropna()
review_df['직무'].unique()

array(['금융/재무', '기획/경영', '개발', '마케팅/시장조사', '디자인', '전문직', '서비스/고객지원',
       '데이터', '인사/총무', '교육', '영업/제휴', '생산/제조', '미디어/홍보', '유통/무역', '기타',
       '엔지니어링', '연구개발', '생산관리/품질관리', '특수계층/공공', '법률/법무', '의약'],
      dtype=object)

In [6]:
review_df['장점'] = review_df['장점'].str.replace("\n","")
review_df['장점'] = review_df['장점'].str.replace("\r","")
review_df['장점'] = review_df['장점'].str.replace("\t","")
review_df['장점'] = review_df['장점'].str.replace(",","")
review_df['장점'] = review_df['장점'].str.replace(".","")

In [7]:
review_df['단점'] = review_df['단점'].str.replace("\n","")
review_df['단점'] = review_df['단점'].str.replace("\r","")
review_df['단점'] = review_df['단점'].str.replace("\t","")
review_df['단점'] = review_df['단점'].str.replace(",","")
review_df['단점'] = review_df['단점'].str.replace(".","")

In [8]:
review_df['요약'] = review_df['요약'].str.replace("\n","")
review_df['요약'] = review_df['요약'].str.replace("\r","")
review_df['요약'] = review_df['요약'].str.replace("\t","")
review_df['요약'] = review_df['요약'].str.replace(",","")
review_df['요약'] = review_df['요약'].str.replace(".","")

In [9]:
review_df = review_df[['직무', '장점', '단점','별점']]
review_df

,직무,장점,단점,별점
4,금융/재무,워라빌이 철저히 지켜짐 팀 사람들은 좋음 전체적으로 활기찬 느낌,불필요한 회의와 에너지 낭비가 많음 그 에너지를 일하는대 쏟으면 좋갰음,3.0
5,기획/경영,다양한 업종 배이스 직원과 교류 보험사 중 워라벨은 좋은 편인듯,다양한 업종이 모였으나 사일로가 굉장히 높음 협업은 사실상 어렵고 친분 또는 위에서...,3.0
6,개발,부바부지만 워라벨이 좋습니다 일정조율이나 이런 부분도 먼저 물어보고 조율을 합니다 ...,스타트업 마인드와 대기업마인드가 적당히 안좋게 섞여있습니다 일단 프로젝트를 진행할때...,4.0
7,금융/재무,워라밸 좋음일안하는or하기싫은 사람에게는 천국유한 분위기 아무튼 30글자,팀장 이상급부터 급격한 질저하그에따른 하루가 멀다하고 바뀌는 형편없는 지시들그에 따...,4.0
8,개발,성장성이 높은 기업이며대기업의 장점 과 스타트업 장점이 있는곳지하철이 연결됨+초고층...,대기업의 단점 과 스타트업 단점이 있는곳성장하는 조직이다 보니 넓게 많은걸 해야함팀...,5.0
...,...,...,...,...
48465,영업/제휴,구내식당이 있어 식비가 안들어서 좋다 시설이 깨끗하고 화장실이 깔끔해서 이용하기 좋...,사무실 청소해주는 사람이 없어서 매우 더럽다 임원방은 막내들이 청소함 야근이 많다 ...,3.0
48466,전문직,예전에는 돈이라고 했던 것 같은데 저는 별로 와 닿지 않네요영업쪽은 경력 쌓으면 이...,회사가 속이 빈 느낌 입니다안을 채우고 싶어도 기존에 계신 분들이 좀 갑갑합니다같이...,1.0
48467,영업/제휴,연봉이 동종 업계에서는 많은편에 속하고 업무강도가 빡쎄기에 다른데 이직하면 좀 더 ...,같은 보고서가 여러개 시스템을 사용하는데 그걸 사용하지 않고 계속 취합함,3.0
48468,생산/제조,연봉은 그냥 평범인센을 잘줌사무실 외관이 이쁘고 핸드백 제조 업계에서는 넘버원입니다,연차 쓰는거에 눈치 엄청 줌 고인물 많고 직원 복지 없었던걸로 기억 동네가 의왕이라...,2.0
48469,유통/무역,1년의 2번 나오는 성과금 수준은 업계 최고 수준입니다사내 식당이 있어 밥 걱정 할...,단순업무가 매우 많으며 각 부서 직무별 업무영역과 책임이 불분명하여 문제 발생시 해...,1.0

In [10]:
review_df['장점']= review_df['장점'].str.replace(pat=r'[^\w]',repl=r' ',regex=True)
review_df['단점']= review_df['단점'].str.replace(pat=r'[^\w]',repl=r' ',regex=True)

In [11]:
review_df_type = review_df.groupby('직무')['별점']
review_df_type.count()

직무
개발           10277
교육             911
금융/재무          838
기타             178
기획/경영         6968
데이터            568
디자인           2788
마케팅/시장조사      6768
미디어/홍보        2569
법률/법무           64
생산/제조         1902
생산관리/품질관리      991
서비스/고객지원      3753
엔지니어링          470
연구개발          1481
영업/제휴         4380
유통/무역         1050
의약              63
인사/총무          813
전문직            407
특수계층/공공         27
Name: 별점, dtype: int64

In [12]:
review_df['별점'].value_counts()

별점
3.0    15222
4.0     9861
2.0     8651
1.0     8409
5.0     5123
Name: count, dtype: int64

In [13]:
review_df['리뷰'] = review_df['장점'].map(str) + ". " + review_df['단점'].map(str)
review_df

,직무,장점,단점,별점,리뷰
4,금융/재무,워라빌이 철저히 지켜짐 팀 사람들은 좋음 전체적으로 활기찬 느낌,불필요한 회의와 에너지 낭비가 많음 그 에너지를 일하는대 쏟으면 좋갰음,3.0,워라빌이 철저히 지켜짐 팀 사람들은 좋음 전체적으로 활기찬 느낌. 불필요한 회의와 ...
5,기획/경영,다양한 업종 배이스 직원과 교류 보험사 중 워라벨은 좋은 편인듯,다양한 업종이 모였으나 사일로가 굉장히 높음 협업은 사실상 어렵고 친분 또는 위에서...,3.0,다양한 업종 배이스 직원과 교류 보험사 중 워라벨은 좋은 편인듯. 다양한 업종이 모...
6,개발,부바부지만 워라벨이 좋습니다 일정조율이나 이런 부분도 먼저 물어보고 조율을 합니다 ...,스타트업 마인드와 대기업마인드가 적당히 안좋게 섞여있습니다 일단 프로젝트를 진행할때...,4.0,부바부지만 워라벨이 좋습니다 일정조율이나 이런 부분도 먼저 물어보고 조율을 합니다 ...
7,금융/재무,워라밸 좋음일안하는or하기싫은 사람에게는 천국유한 분위기 아무튼 30글자,팀장 이상급부터 급격한 질저하그에따른 하루가 멀다하고 바뀌는 형편없는 지시들그에 따...,4.0,워라밸 좋음일안하는or하기싫은 사람에게는 천국유한 분위기 아무튼 30글자. 팀장 이...
8,개발,성장성이 높은 기업이며대기업의 장점 과 스타트업 장점이 있는곳지하철이 연결됨 초고층...,대기업의 단점 과 스타트업 단점이 있는곳성장하는 조직이다 보니 넓게 많은걸 해야함팀...,5.0,성장성이 높은 기업이며대기업의 장점 과 스타트업 장점이 있는곳지하철이 연결됨 초고층...
...,...,...,...,...,...
48465,영업/제휴,구내식당이 있어 식비가 안들어서 좋다 시설이 깨끗하고 화장실이 깔끔해서 이용하기 좋...,사무실 청소해주는 사람이 없어서 매우 더럽다 임원방은 막내들이 청소함 야근이 많다 ...,3.0,구내식당이 있어 식비가 안들어서 좋다 시설이 깨끗하고 화장실이 깔끔해서 이용하기 좋...
48466,전문직,예전에는 돈이라고 했던 것 같은데 저는 별로 와 닿지 않네요영업쪽은 경력 쌓으면 이...,회사가 속이 빈 느낌 입니다안을 채우고 싶어도 기존에 계신 분들이 좀 갑갑합니다같이...,1.0,예전에는 돈이라고 했던 것 같은데 저는 별로 와 닿지 않네요영업쪽은 경력 쌓으면 이...
48467,영업/제휴,연봉이 동종 업계에서는 많은편에 속하고 업무강도가 빡쎄기에 다른데 이직하면 좀 더 ...,같은 보고서가 여러개 시스템을 사용하는데 그걸 사용하지 않고 계속 취합함,3.0,연봉이 동종 업계에서는 많은편에 속하고 업무강도가 빡쎄기에 다른데 이직하면 좀 더 ...
48468,생산/제조,연봉은 그냥 평범인센을 잘줌사무실 외관이 이쁘고 핸드백 제조 업계에서는 넘버원입니다,연차 쓰는거에 눈치 엄청 줌 고인물 많고 직원 복지 없었던걸로 기억 동네가 의왕이라...,2.0,연봉은 그냥 평범인센을 잘줌사무실 외관이 이쁘고 핸드백 제조 업계에서는 넘버원입니다...
48469,유통/무역,1년의 2번 나오는 성과금 수준은 업계 최고 수준입니다사내 식당이 있어 밥 걱정 할...,단순업무가 매우 많으며 각 부서 직무별 업무영역과 책임이 불분명하여 문제 발생시 해...,1.0,1년의 2번 나오는 성과금 수준은 업계 최고 수준입니다사내 식당이 있어 밥 걱정 할...

In [14]:
review_df_po = review_df[['직무', '장점']]
review_df_po['라벨'] = 1
review_df_po.rename(columns = {'장점' : '장단점'}, inplace = True)
review_df_ne = review_df[['직무', '단점']]
review_df_ne['라벨'] = 0
review_df_ne.rename(columns = {'단점' : '장단점'}, inplace = True)
review_df_new = pd.concat([review_df_po, review_df_ne], ignore_index=True)
review_df_new

C:\Users\sunga\AppData\Local\Temp\ipykernel_19596\4059907017.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  review_df_po['라벨'] = 1
C:\Users\sunga\AppData\Local\Temp\ipykernel_19596\4059907017.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  review_df_ne['라벨'] = 0

,직무,장점,라벨,단점
0,금융/재무,워라빌이 철저히 지켜짐 팀 사람들은 좋음 전체적으로 활기찬 느낌,1,NaN
1,기획/경영,다양한 업종 배이스 직원과 교류 보험사 중 워라벨은 좋은 편인듯,1,NaN
2,개발,부바부지만 워라벨이 좋습니다 일정조율이나 이런 부분도 먼저 물어보고 조율을 합니다 ...,1,NaN
3,금융/재무,워라밸 좋음일안하는or하기싫은 사람에게는 천국유한 분위기 아무튼 30글자,1,NaN
4,개발,성장성이 높은 기업이며대기업의 장점 과 스타트업 장점이 있는곳지하철이 연결됨 초고층...,1,NaN
...,...,...,...,...
94527,영업/제휴,NaN,0,사무실 청소해주는 사람이 없어서 매우 더럽다 임원방은 막내들이 청소함 야근이 많다 ...
94528,전문직,NaN,0,회사가 속이 빈 느낌 입니다안을 채우고 싶어도 기존에 계신 분들이 좀 갑갑합니다같이...
94529,영업/제휴,NaN,0,같은 보고서가 여러개 시스템을 사용하는데 그걸 사용하지 않고 계속 취합함
94530,생산/제조,NaN,0,연차 쓰는거에 눈치 엄청 줌 고인물 많고 직원 복지 없었던걸로 기억 동네가 의왕이라...
94531,유통/무역,NaN,0,단순업무가 매우 많으며 각 부서 직무별 업무영역과 책임이 불분명하여 문제 발생시 해...

In [15]:
selected = ['데이터','디자인']
review_df_test =review_df_new[review_df_new['직무'].isin(selected)].reset_index(drop=True)
review_df_test

,직무,장점,라벨,단점
0,디자인,직원분들이 좋으시고 그래도 분위기는 좋은 편인 것 같다 회사 위치도 괜찮은 편이고 ...,1,NaN
1,데이터,평등하고 워라벨이 좋은 편이고잘 생각이 안날 정도로 정이 떨어졌다,1,NaN
2,디자인,야근 없고 연차 눈치 안보고 쓸 수 있는거 그리고 없네요,1,NaN
3,디자인,연차를 눈치보지 않고 쓸 수 있음 휴가도 자유롭게 사용가능,1,NaN
4,데이터,타기업 대비 높은 연봉노멀한 사내 분위기스무스한 직원들는 다른 곳보다 너무 좋고 특...,1,NaN
...,...,...,...,...
6707,디자인,NaN,0,야근을 권장 안한다면서 야근하는 사람을 좋아하는 경향이 있음알수없는 타임레포트 세계
6708,디자인,NaN,0,고정 출퇴근시간이 있는데 마음대로 출퇴근하는 사람들이 있어 힘듭니다 점심출근이나 이...
6709,디자인,NaN,0,조직체계가 잡히지않아 아직 업무진행에 어려움이 따름점차 개선은 되고 있으니 조금 시...
6710,디자인,NaN,0,돈이적다 복지가 별로없다 신입들이 줄줄이 퇴사한다 기숙사가 더럽다 사람들도 더럽다
6711,디자인,NaN,0,세계 최대의 가방벤더 답게 연봉도 높고 브랜드들도 유명하고 기타등등 화사에 대한 대...

In [16]:
review_df_test.to_csv('review_df_test_po.txt', sep ='\t', index = False)

In [17]:
review_df_train = review_df_new[~review_df_new['직무'].isin(selected)].reset_index(drop=True)
review_df_train = review_df_train[['장점','라벨']]
review_df_train

KeyError: "['별점'] not in index"

In [ ]:
review_df_train['별점'] = review_df_train['별점'].astype(int)
review_df_train['별점']

0        3
1        3
2        4
3        4
4        5
        ..
43905    3
43906    1
43907    3
43908    2
43909    1
Name: 별점, Length: 43910, dtype: int32

In [ ]:
review_df_train['별점'] = review_df_train['별점'] -1
review_df_train['별점']

0        2
1        2
2        3
3        3
4        4
        ..
43905    2
43906    0
43907    2
43908    1
43909    0
Name: 별점, Length: 43910, dtype: int32

In [ ]:
review_df_train.to_csv('review_df_train2.txt', sep ='\t', index = False)